#Entendendo o problema

In [ ]:
import pandas as pd

In [ ]:
dados_hospedagem = pd.read_json("/content/dados_hospedagem.json")
dados_hospedagem = pd.json_normalize(dados_hospedagem["info_moveis"])
dados_hospedagem

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,[This clean and comfortable one bedroom sits r...,[Lower Queen Anne is near the Seattle Center (...,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[Real Bed, Futon, Futon, Pull-out Sofa, Real B...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$0, $0, $0, $0, $0, $350.00, $350.00, $350.00...","[$0, $0, $0, $20.00, $15.00, $28.00, $35.00, $...","[$110.00, $45.00, $55.00, $52.00, $85.00, $50...."
1,10.0,--,10,[Welcome to the heart of the 'Ballard Brewery ...,"[--, Capital Hill is the heart of Seattle, bor...","[2, 3, 2, 3, 3, 3, 2, 1, 2, 2, 2]","[3, 4, 2, 3, 3, 3, 3, 3, 3, 4, 3]","[5, 6, 8, 3, 3, 5, 4, 5, 6, 7, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$500.00, $300.00, $0, $300.00, $300.00, $360....","[$125.00, $100.00, $85.00, $110.00, $110.00, $...","[$350.00, $300.00, $425.00, $300.00, $285.00, ..."
2,10.0,--,11,[New modern house built in 2013. Spectacular ...,[Upper Queen Anne is a charming neighborhood f...,[4],[5],[7],[Real Bed],"[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$1,000.00]",[$300.00],[$975.00]
3,10.0,--,12,[Our NW style home is 3200+ sq ft with 3 level...,[The Views from our top floor! Wallingford ha...,"[3, 3, 3, 3, 3, 3, 3, 3]","[6, 6, 5, 5, 5, 5, 4, 4]","[6, 6, 7, 8, 7, 7, 6, 6]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{Internet,""Wireless Internet"",Kitchen,""Free P...","[$500.00, $500.00, $500.00, $500.00, $500.00, ...","[$225.00, $300.00, $250.00, $250.00, $250.00, ...","[$490.00, $550.00, $350.00, $350.00, $350.00, ..."
4,10.0,--,14,"[Perfect for groups. 2 bedrooms, full bathroom...",[Safeway grocery store within walking distance...,"[2, 3]","[2, 6]","[3, 9]","[Real Bed, Real Bed]","[{TV,Internet,""Wireless Internet"",Kitchen,""Fre...","[$300.00, $2,000.00]","[$40.00, $150.00]","[$200.00, $545.00]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,nan,--,5,[Our cozy little bungalow is the perfect place...,[The Queen Anne neighborhood is one of the mos...,"[1, 3, 2, 2, 2, 1, 2, 1, 1, 1, 2, 3, 2, 2, 2, ...","[2, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, ...","[3, 2, 2, 3, 3, 2, 3, 2, 2, 3, 3, 3, 2, 3, 2, ...","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{""Cable TV"",""Wireless Internet"",Kitchen,""Free...","[$250.00, $200.00, $0, $0, $0, $200.00, $350.0...","[$35.00, $50.00, $100.00, $100.00, $0, $30.00,...","[$150.00, $200.00, $143.00, $150.00, $350.00, ..."
66,nan,--,6,[Bright clean 2 bedroom 1 bath appartment in t...,[Ballard is the most interesting and ecclectic...,"[1, 1, 3, 2, 1, 3, 2, 2, 1, 2, 2, 2, 1, 2, 1, ...","[2, 3, 3, 2, 2, 3, 2, 3, 2, 2, 2, 2, 4, 3, 3, ...","[3, 3, 2, 3, 3, 3, 2, 3, 3, 3, 2, 2, 4, 4, 3, ...","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,""Cable TV"",Internet,""Wireless Internet"",K...","[$200.00, $200.00, $100.00, $0, $0, $750.00, $...","[$0, $0, $100.00, $0, $75.00, $140.00, $112.00...","[$99.00, $185.00, $250.00, $200.00, $275.00, $..."
67,nan,--,7,[Beautiful end-unit townhome with lots of dayl...,"[Cherry blossoms (Sakura) in the spring, every...","[4, 3, 1, 2, 2, 1, 2, 1, 2, 2]","[3, 4, 3, 3, 3, 3, 3, 3, 3, 4]","[3, 5, 1, 5, 3, 2, 3, 4, 4, 4]","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$750.00, $350.00, $500.00, $500.00, $0, $200....","[$300.00, $90.00, $250.00, $100.00, $109.00, $...","[$218.00, $350.00, $450.00, $149.00, $99.00, $..."
68,nan,--,8,[Heart of Ballard new townhome with 4 BRs + ba...,"[--, --, The suite is conveniently located off...","[2, 2, 3, 1, 1, 2, 1, 3, 2, 1, 2, 1, 2, 2, 2, ...","[4, 2, 3, 4, 3, 3, 4, 4, 3, 5, 2, 3, 3, 4, 5, ...","[4, 4, 3, 3, 5, 5, 5, 5, 3, 5, 4, 5, 5, 4, 1, ...","[Real Bed, Real Bed, Real Bed, Real Bed, Real ...","[{TV,Internet,""Wireless Internet"",""Air Conditi...","[$500.00, $150.00, $250.00, $800.00, $0, $500....","[$50.00, $85.00, $150.00, $75.00, $100.00, $80...","[$275.00, $199.00, $400.00, $325.00, $300.00, ..."
69,nan,--,9,[This business-themed modern home features: *...,[Your hosts made Madison Valley their home whe...,"[2, 1]","[3, 4]","[6, 6]","[Real Bed, Real Bed]","[{TV,""Cable TV"",Internet,""Wireless Internet"",""...","[$1,000.00, $500.00]","[$150.00, $0]","[$250.00, $350.00]"

#Desafio

In [ ]:
dados_vendas = pd.read_json("/content/dados_vendas_clientes.json")
dados_vendas = pd.json_normalize(dados_vendas["dados_vendas"])
dados_vendas

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

In [ ]:
dados_imoveis = pd.read_json("/content/dados_locacao_imoveis.json")
dados_imoveis = pd.json_normalize(dados_imoveis["dados_locacao"])
dados_imoveis

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"
5,C302 (blocoAP),"[06/06/2022, 06/07/2022]","[08/06/2022, 12/07/2022]","[$ 1500,0 reais, $ 1200,0 reais]"
6,D401 (blocoAP),"[07/06/2022, 07/07/2022]","[07/06/2022, 09/07/2022]","[$ 1600,0 reais, $ 1300,0 reais]"
7,D402 (blocoAP),"[08/06/2022, 08/07/2022]","[10/06/2022, 14/07/2022]","[$ 1700,0 reais, $ 1400,0 reais]"
8,E501 (blocoAP),"[09/06/2022, 09/07/2022]","[10/06/2022, 09/07/2022]","[$ 1800,0 reais, $ 1500,0 reais]"
9,E502 (blocoAP),"[10/06/2022, 10/07/2022]","[16/06/2022, 12/07/2022]","[$ 1900,0 reais, $ 1600,0 reais]"
10,F601 (blocoAP),"[11/06/2022, 11/07/2022]","[17/06/2022, 13/07/2022]","[$ 2000,0 reais, $ 1000,0 reais]"
11,F602 (blocoAP),"[12/06/2022, 12/07/2022]","[15/06/2022, 12/07/2022]","[$ 2100,0 reais, $ 1100,0 reais]"
12,G701 (blocoAP),"[13/06/2022, 13/07/2022]","[19/06/2022, 20/07/2022]","[$ 2200,0 reais, $ 1200,0 reais]"
13,G702 (blocoAP),"[14/06/2022, 14/07/2022]","[15/06/2022, 17/07/2022]","[$ 2300,0 reais, $ 2100,0 reais]"
14,H801 (blocoAP),"[15/06/2022, 15/07/2022]","[18/06/2022, 16/07/2022]","[$ 2400,0 reais, $ 2200,0 reais]"

#Dados numéricos

In [ ]:
colunas = list(dados_hospedagem.columns)
colunas

['avaliacao_geral',
 'experiencia_local',
 'max_hospedes',
 'descricao_local',
 'descricao_vizinhanca',
 'quantidade_banheiros',
 'quantidade_quartos',
 'quantidade_camas',
 'modelo_cama',
 'comodidades',
 'taxa_deposito',
 'taxa_limpeza',
 'preco']

In [ ]:
colunas = colunas[3:]
colunas

['descricao_local',
 'descricao_vizinhanca',
 'quantidade_banheiros',
 'quantidade_quartos',
 'quantidade_camas',
 'modelo_cama',
 'comodidades',
 'taxa_deposito',
 'taxa_limpeza',
 'preco']

In [ ]:
dados_hospedagem = dados_hospedagem.explode(colunas)
dados_hospedagem

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
0,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
0,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
0,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
0,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
68,nan,--,8,Beautiful craftsman home in the historic Wedgw...,--,3,4,5,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$178.00,$299.00
68,nan,--,8,Located in a very easily accessible area of Se...,"Quiet, dead end street near I-5. The proximity...",2,4,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",$0,$99.00,$199.00
68,nan,--,8,This home is fully furnished and available wee...,--,1,3,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",$0,$0,$400.00
69,nan,--,9,This business-themed modern home features: *H...,Your hosts made Madison Valley their home when...,2,3,6,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$150.00,$250.00
69,nan,--,9,This welcoming home is in the quiet residentia...,"Despite the quiet, leafy streets of this resid...",1,4,6,Real Bed,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$500.00,$0,$350.00

In [ ]:
dados_hospedagem.reset_index(inplace=True,drop=True)
dados_hospedagem

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,$110.00
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$45.00
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,$55.00
3,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,$52.00
4,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,$85.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3813,nan,--,8,Beautiful craftsman home in the historic Wedgw...,--,3,4,5,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$178.00,$299.00
3814,nan,--,8,Located in a very easily accessible area of Se...,"Quiet, dead end street near I-5. The proximity...",2,4,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",$0,$99.00,$199.00
3815,nan,--,8,This home is fully furnished and available wee...,--,1,3,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",$0,$0,$400.00
3816,nan,--,9,This business-themed modern home features: *H...,Your hosts made Madison Valley their home when...,2,3,6,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$150.00,$250.00
3817,nan,--,9,This welcoming home is in the quiet residentia...,"Despite the quiet, leafy streets of this resid...",1,4,6,Real Bed,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$500.00,$0,$350.00

In [ ]:
dados_hospedagem.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   object
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   object
 6   quantidade_quartos    3818 non-null   object
 7   quantidade_camas      3818 non-null   object
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   object
dtypes: object(13)
memory usage: 387.9+ KB

In [ ]:
import numpy as np

In [ ]:
dados_hospedagem["max_hospedes"] = dados_hospedagem["max_hospedes"].astype(np.int64)
dados_hospedagem.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   object
 6   quantidade_quartos    3818 non-null   object
 7   quantidade_camas      3818 non-null   object
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   object
dtypes: int64(1), object(12)
memory usage: 387.9+ KB

In [ ]:
colunas_numericas = ["quantidade_banheiros","quantidade_quartos","quantidade_camas"]

In [ ]:
dados_hospedagem[colunas_numericas] = dados_hospedagem[colunas_numericas].astype(np.int64)
dados_hospedagem.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   object
dtypes: int64(4), object(9)
memory usage: 387.9+ KB

In [ ]:
dados_hospedagem["avaliacao_geral"] = dados_hospedagem["avaliacao_geral"].astype(np.float64)
dados_hospedagem.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   object
dtypes: float64(1), int64(4), object(8)
memory usage: 387.9+ KB

In [ ]:
dados_hospedagem["preco"]

0       $110.00
1        $45.00
2        $55.00
3        $52.00
4        $85.00
         ...
3813    $299.00
3814    $199.00
3815    $400.00
3816    $250.00
3817    $350.00
Name: preco, Length: 3818, dtype: object

In [ ]:
dados_hospedagem["preco"] = dados_hospedagem["preco"].apply(lambda x: x.replace("$","").replace(",","").strip())
dados_hospedagem

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,This clean and comfortable one bedroom sits ri...,Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$0,110.00
1,10.0,--,1,Our century old Upper Queen Anne house is loca...,"Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,45.00
2,10.0,--,1,Cozy room in two-bedroom apartment along the l...,The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$0,$0,55.00
3,10.0,--,1,Very lovely and cozy room for one. Convenientl...,"Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",$0,$20.00,52.00
4,10.0,--,1,The “Studio at Mibbett Hollow' is in a Beautif...,--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",$0,$15.00,85.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3813,NaN,--,8,Beautiful craftsman home in the historic Wedgw...,--,3,4,5,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$178.00,299.00
3814,NaN,--,8,Located in a very easily accessible area of Se...,"Quiet, dead end street near I-5. The proximity...",2,4,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",$0,$99.00,199.00
3815,NaN,--,8,This home is fully furnished and available wee...,--,1,3,4,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...",$0,$0,400.00
3816,NaN,--,9,This business-themed modern home features: *H...,Your hosts made Madison Valley their home when...,2,3,6,Real Bed,"{TV,""Cable TV"",Internet,""Wireless Internet"",""A...","$1,000.00",$150.00,250.00
3817,NaN,--,9,This welcoming home is in the quiet residentia...,"Despite the quiet, leafy streets of this resid...",1,4,6,Real Bed,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",$500.00,$0,350.00

In [ ]:
dados_hospedagem["preco"] = dados_hospedagem["preco"].astype(np.float64)
dados_hospedagem.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   float64
dtypes: float64(2), int64(4), object(7)
memory usage: 387.9+ KB

In [ ]:
dados_hospedagem[["taxa_deposito","taxa_limpeza"]] = dados_hospedagem[["taxa_deposito","taxa_limpeza"]].applymap(lambda x: x.replace("$","").replace(",","").strip())

<ipython-input-118-78037b9ebae2>:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  dados_hospedagem[["taxa_deposito","taxa_limpeza"]] = dados_hospedagem[["taxa_deposito","taxa_limpeza"]].applymap(lambda x: x.replace("$","").replace(",","").strip())

In [ ]:
dados_hospedagem[["taxa_deposito","taxa_limpeza"]] = dados_hospedagem[["taxa_deposito","taxa_limpeza"]].astype(np.float64)
dados_hospedagem.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3162 non-null   float64
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   int64
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   int64
 6   quantidade_quartos    3818 non-null   int64
 7   quantidade_camas      3818 non-null   int64
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   float64
 11  taxa_limpeza          3818 non-null   float64
 12  preco                 3818 non-null   float64
dtypes: float64(4), int64(4), object(5)
memory usage: 387.9+ KB

#Desafio 2

1.1.Remover os dados em listas dentro do DataFrame;

In [ ]:
dados_vendas

,Data de venda,Cliente,Valor da compra
0,06/06/2022,"[@ANA _LUCIA 321, DieGO ARMANDIU 210, DieGO AR...","[R$ 836,5, R$ 573,33, R$ 392,8, R$ 512,34]"
1,07/06/2022,"[Isabely JOanes 738, Isabely JOanes 738, Isabe...","[R$ 825,31, R$ 168,07, R$ 339,18, R$ 314,69]"
2,08/06/2022,"[Isabely JOanes 738, JOãO Gabriel 671, Julya m...","[R$ 682,05, R$ 386,34, R$ 622,65, R$ 630,79]"
3,09/06/2022,"[Julya meireles 914, MaRIA Julia 444, MaRIA Ju...","[R$ 390,3, R$ 759,16, R$ 334,47, R$ 678,78]"
4,10/06/2022,"[MaRIA Julia 444, PEDRO PASCO 812, Paulo castr...","[R$ 314,24, R$ 311,15, R$ 899,16, R$ 885,24]"

In [ ]:
colunas_explodir = ["Cliente","Valor da compra"]
dados_vendas = dados_vendas.explode(colunas_explodir)
dados_vendas

  Data de venda             Cliente Valor da compra
0    06/06/2022     @ANA _LUCIA 321        R$ 836,5
0    06/06/2022  DieGO ARMANDIU 210       R$ 573,33
0    06/06/2022  DieGO ARMANDIU 210        R$ 392,8
0    06/06/2022  DieGO ARMANDIU 210       R$ 512,34
1    07/06/2022  Isabely JOanes 738       R$ 825,31
1    07/06/2022  Isabely JOanes 738       R$ 168,07
1    07/06/2022  Isabely JOanes 738       R$ 339,18
1    07/06/2022  Isabely JOanes 738       R$ 314,69
2    08/06/2022  Isabely JOanes 738       R$ 682,05
2    08/06/2022    JOãO Gabriel 671       R$ 386,34
2    08/06/2022  Julya meireles 914       R$ 622,65
2    08/06/2022  Julya meireles 914       R$ 630,79
3    09/06/2022  Julya meireles 914        R$ 390,3
3    09/06/2022     MaRIA Julia 444       R$ 759,16
3    09/06/2022     MaRIA Julia 444       R$ 334,47
3    09/06/2022     MaRIA Julia 444       R$ 678,78
4    10/06/2022     MaRIA Julia 444       R$ 314,24
4    10/06/2022     PEDRO PASCO 812       R$ 311,15
4    10/06/2022    Paulo castro 481       R$ 899,16
4    10/06/2022   Thiago fritzz 883       R$ 885,24

1.2.Verificar os tipos de dados;

In [ ]:
dados_vendas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 0 to 4
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     object
dtypes: object(3)
memory usage: 1.2+ KB

1.3.Transformar a coluna numérica para o tipo numérico.

In [ ]:
dados_vendas['Valor da compra'] = dados_vendas['Valor da compra'].apply(lambda x: x.replace('R$ ', '').replace(',', '.').strip())
dados_vendas['Valor da compra'] = dados_vendas['Valor da compra'].astype(float)
dados_vendas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 0 to 4
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: float64(1), object(2)
memory usage: 1.2+ KB

In [ ]:
dados_vendas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 0 to 4
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: float64(1), object(2)
memory usage: 1.2+ KB

2.1.Remover os dados em listas dentro do DataFrame;

In [ ]:
dados_imoveis

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),"[01/06/2022, 01/07/2022]","[05/06/2022, 03/07/2022]","[$ 1000,0 reais, $ 2500,0 reais]"
1,A102 (blocoAP),"[02/06/2022, 02/07/2022]","[02/06/2022, 06/07/2022]","[$ 1100,0 reais, $ 2600,0 reais]"
2,B201 (blocoAP),"[03/06/2022, 03/07/2022]","[07/06/2022, 03/07/2022]","[$ 1200,0 reais, $ 2700,0 reais]"
3,B202 (blocoAP),"[04/06/2022, 04/07/2022]","[07/06/2022, 05/07/2022]","[$ 1300,0 reais, $ 2800,0 reais]"
4,C301 (blocoAP),"[05/06/2022, 05/07/2022]","[10/06/2022, 09/07/2022]","[$ 1400,0 reais, $ 2900,0 reais]"
5,C302 (blocoAP),"[06/06/2022, 06/07/2022]","[08/06/2022, 12/07/2022]","[$ 1500,0 reais, $ 1200,0 reais]"
6,D401 (blocoAP),"[07/06/2022, 07/07/2022]","[07/06/2022, 09/07/2022]","[$ 1600,0 reais, $ 1300,0 reais]"
7,D402 (blocoAP),"[08/06/2022, 08/07/2022]","[10/06/2022, 14/07/2022]","[$ 1700,0 reais, $ 1400,0 reais]"
8,E501 (blocoAP),"[09/06/2022, 09/07/2022]","[10/06/2022, 09/07/2022]","[$ 1800,0 reais, $ 1500,0 reais]"
9,E502 (blocoAP),"[10/06/2022, 10/07/2022]","[16/06/2022, 12/07/2022]","[$ 1900,0 reais, $ 1600,0 reais]"
10,F601 (blocoAP),"[11/06/2022, 11/07/2022]","[17/06/2022, 13/07/2022]","[$ 2000,0 reais, $ 1000,0 reais]"
11,F602 (blocoAP),"[12/06/2022, 12/07/2022]","[15/06/2022, 12/07/2022]","[$ 2100,0 reais, $ 1100,0 reais]"
12,G701 (blocoAP),"[13/06/2022, 13/07/2022]","[19/06/2022, 20/07/2022]","[$ 2200,0 reais, $ 1200,0 reais]"
13,G702 (blocoAP),"[14/06/2022, 14/07/2022]","[15/06/2022, 17/07/2022]","[$ 2300,0 reais, $ 2100,0 reais]"
14,H801 (blocoAP),"[15/06/2022, 15/07/2022]","[18/06/2022, 16/07/2022]","[$ 2400,0 reais, $ 2200,0 reais]"

In [ ]:
colunas_explodir = ["datas_combinadas_pagamento","datas_de_pagamento","valor_aluguel"]
dados_imoveis = dados_imoveis.explode(colunas_explodir)
dados_imoveis

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,"$ 1000,0 reais"
0,A101 (blocoAP),01/07/2022,03/07/2022,"$ 2500,0 reais"
1,A102 (blocoAP),02/06/2022,02/06/2022,"$ 1100,0 reais"
1,A102 (blocoAP),02/07/2022,06/07/2022,"$ 2600,0 reais"
2,B201 (blocoAP),03/06/2022,07/06/2022,"$ 1200,0 reais"
2,B201 (blocoAP),03/07/2022,03/07/2022,"$ 2700,0 reais"
3,B202 (blocoAP),04/06/2022,07/06/2022,"$ 1300,0 reais"
3,B202 (blocoAP),04/07/2022,05/07/2022,"$ 2800,0 reais"
4,C301 (blocoAP),05/06/2022,10/06/2022,"$ 1400,0 reais"
4,C301 (blocoAP),05/07/2022,09/07/2022,"$ 2900,0 reais"
5,C302 (blocoAP),06/06/2022,08/06/2022,"$ 1500,0 reais"
5,C302 (blocoAP),06/07/2022,12/07/2022,"$ 1200,0 reais"
6,D401 (blocoAP),07/06/2022,07/06/2022,"$ 1600,0 reais"
6,D401 (blocoAP),07/07/2022,09/07/2022,"$ 1300,0 reais"
7,D402 (blocoAP),08/06/2022,10/06/2022,"$ 1700,0 reais"
7,D402 (blocoAP),08/07/2022,14/07/2022,"$ 1400,0 reais"
8,E501 (blocoAP),09/06/2022,10/06/2022,"$ 1800,0 reais"
8,E501 (blocoAP),09/07/2022,09/07/2022,"$ 1500,0 reais"
9,E502 (blocoAP),10/06/2022,16/06/2022,"$ 1900,0 reais"
9,E502 (blocoAP),10/07/2022,12/07/2022,"$ 1600,0 reais"
10,F601 (blocoAP),11/06/2022,17/06/2022,"$ 2000,0 reais"
10,F601 (blocoAP),11/07/2022,13/07/2022,"$ 1000,0 reais"
11,F602 (blocoAP),12/06/2022,15/06/2022,"$ 2100,0 reais"
11,F602 (blocoAP),12/07/2022,12/07/2022,"$ 1100,0 reais"
12,G701 (blocoAP),13/06/2022,19/06/2022,"$ 2200,0 reais"
12,G701 (blocoAP),13/07/2022,20/07/2022,"$ 1200,0 reais"
13,G702 (blocoAP),14/06/2022,15/06/2022,"$ 2300,0 reais"
13,G702 (blocoAP),14/07/2022,17/07/2022,"$ 2100,0 reais"
14,H801 (blocoAP),15/06/2022,18/06/2022,"$ 2400,0 reais"
14,H801 (blocoAP),15/07/2022,16/07/2022,"$ 2200,0 reais"

2.2.Verificar os tipos de dados;

In [ ]:
dados_imoveis.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 0 to 14
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     object
dtypes: object(4)
memory usage: 1.2+ KB

2.3.Transformar a coluna numérica para o tipo numérico.

In [ ]:
dados_imoveis["valor_aluguel"] = dados_imoveis["valor_aluguel"].apply(lambda x: x.replace("$ ","").replace("reais","").replace(",",".").strip())
dados_imoveis["valor_aluguel"]

0     1000.0
0     2500.0
1     1100.0
1     2600.0
2     1200.0
2     2700.0
3     1300.0
3     2800.0
4     1400.0
4     2900.0
5     1500.0
5     1200.0
6     1600.0
6     1300.0
7     1700.0
7     1400.0
8     1800.0
8     1500.0
9     1900.0
9     1600.0
10    2000.0
10    1000.0
11    2100.0
11    1100.0
12    2200.0
12    1200.0
13    2300.0
13    2100.0
14    2400.0
14    2200.0
Name: valor_aluguel, dtype: object

In [ ]:
dados_imoveis["valor_aluguel"] = dados_imoveis["valor_aluguel"].astype(np.float64)
dados_imoveis["valor_aluguel"]

0     1000.0
0     2500.0
1     1100.0
1     2600.0
2     1200.0
2     2700.0
3     1300.0
3     2800.0
4     1400.0
4     2900.0
5     1500.0
5     1200.0
6     1600.0
6     1300.0
7     1700.0
7     1400.0
8     1800.0
8     1500.0
9     1900.0
9     1600.0
10    2000.0
10    1000.0
11    2100.0
11    1100.0
12    2200.0
12    1200.0
13    2300.0
13    2100.0
14    2400.0
14    2200.0
Name: valor_aluguel, dtype: float64

#Dados textuais

In [ ]:
dados_hospedagem["descricao_local"] = dados_hospedagem["descricao_local"].str.lower()
dados_hospedagem["descricao_local"].head()

0    this clean and comfortable one bedroom sits ri...
1    our century old upper queen anne house is loca...
2    cozy room in two-bedroom apartment along the l...
3    very lovely and cozy room for one. convenientl...
4    the “studio at mibbett hollow' is in a beautif...
Name: descricao_local, dtype: object

In [ ]:
dados_hospedagem["descricao_local"][77]

'maple creek house  we have pleasant furnished rooms for rent in a cheerful artistic house in wedgwood just a bit north of uw. use this site is for booking the larger garden view room which has hardwood floors. see our other listings (on right sidebar) for our maple creek house medium bedroom or the study den, a pleasant semi-secluded garden level room with a separate entrance and mini frig. for short stays we have art studio, a casual space with a daybed and sliding glass patio doors. we often have guests who are grad students or working folks in town who are on projects. our place is quiet and spacious with a veggie garden and woodsy yard and we share a unique circular central kitchen, bath, common living room, free off street parking. fireplace, hardwood floors, garden views. always available parking, dishwasher/washer/dryer and wifi, we are a non-smoking home. two blocks to buses, stores, banks and internet cafes, 10 min to the uw by car, also bikable , great walking neighborhood, n'

In [ ]:
dados_hospedagem["descricao_local"] = dados_hospedagem["descricao_local"].str.replace("[^a-zA-Z0-9\-\']"," ",regex=True)

In [ ]:
dados_hospedagem["descricao_local"]= dados_hospedagem["descricao_local"].str.replace("(?<!\w)-(?!\w)"," ",regex=True)

In [ ]:
dados_hospedagem["descricao_local"] = dados_hospedagem["descricao_local"].str.split()

In [ ]:
dados_hospedagem.loc[:5]

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,"[this, clean, and, comfortable, one, bedroom, ...",Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,0.0,110.0
1,10.0,--,1,"[our, century, old, upper, queen, anne, house,...","Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,45.0
2,10.0,--,1,"[cozy, room, in, two-bedroom, apartment, along...",The convenience of being in Seattle but on the...,1,1,1,Futon,"{TV,Internet,""Wireless Internet"",Kitchen,""Free...",0.0,0.0,55.0
3,10.0,--,1,"[very, lovely, and, cozy, room, for, one, conv...","Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"{Internet,""Wireless Internet"",Kitchen,""Free Pa...",0.0,20.0,52.0
4,10.0,--,1,"[the, studio, at, mibbett, hollow', is, in, a,...",--,1,1,1,Real Bed,"{""Wireless Internet"",Kitchen,""Free Parking on ...",0.0,15.0,85.0
5,10.0,--,1,"[built, run, and, supported, by, seattle, tech...",Wallingford is a mostly-residential neighborho...,1,1,1,Real Bed,"{Internet,""Wireless Internet"",Kitchen,""Indoor ...",350.0,28.0,50.0

In [ ]:
dados_hospedagem["comodidades"] = dados_hospedagem["comodidades"].str.replace("\{|}\"","",regex=True)

In [ ]:
dados_hospedagem["comodidades"] = dados_hospedagem["comodidades"].str.split(",")
dados_hospedagem.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,"[this, clean, and, comfortable, one, bedroom, ...",Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"[Internet, ""Wireless Internet"", Kitchen, ""Free...",0.0,0.0,110.0
1,10.0,--,1,"[our, century, old, upper, queen, anne, house,...","Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"[TV, Internet, ""Wireless Internet"", Kitchen, ""...",0.0,0.0,45.0
2,10.0,--,1,"[cozy, room, in, two-bedroom, apartment, along...",The convenience of being in Seattle but on the...,1,1,1,Futon,"[TV, Internet, ""Wireless Internet"", Kitchen, ""...",0.0,0.0,55.0
3,10.0,--,1,"[very, lovely, and, cozy, room, for, one, conv...","Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"[Internet, ""Wireless Internet"", Kitchen, ""Free...",0.0,20.0,52.0
4,10.0,--,1,"[the, studio, at, mibbett, hollow', is, in, a,...",--,1,1,1,Real Bed,"[""Wireless Internet"", Kitchen, ""Free Parking o...",0.0,15.0,85.0

In [ ]:
dados_hospedagem["descricao_vizinhanca"] = dados_hospedagem["descricao_vizinhanca"].str.lower()

In [ ]:
dados_hospedagem["descricao_vizinhanca"] = dados_hospedagem["descricao_vizinhanca"].str.replace("[^a-zA-Z0-9\-\']"," ",regex=True)
dados_hospedagem["descricao_vizinhanca"]

0       lower queen anne is near the seattle center  s...
1       upper queen anne is a really pleasant  unique ...
2       the convenience of being in seattle but on the...
3       ballard is lovely  vibrant and one of the most...
4                                                      --
                              ...
3813                                                   --
3814    quiet  dead end street near i-5  the proximity...
3815                                                   --
3816    your hosts made madison valley their home when...
3817    despite the quiet  leafy streets of this resid...
Name: descricao_vizinhanca, Length: 3818, dtype: object

In [ ]:
dados_hospedagem["descricao_vizinhanca"]= dados_hospedagem["descricao_vizinhanca"].str.replace("(?<!\w)-(?!\w)"," ",regex=True)
dados_hospedagem["descricao_vizinhanca"]

0       lower queen anne is near the seattle center  s...
1       upper queen anne is a really pleasant  unique ...
2       the convenience of being in seattle but on the...
3       ballard is lovely  vibrant and one of the most...
4
                              ...
3813
3814    quiet  dead end street near i-5  the proximity...
3815
3816    your hosts made madison valley their home when...
3817    despite the quiet  leafy streets of this resid...
Name: descricao_vizinhanca, Length: 3818, dtype: object

In [ ]:
dados_hospedagem["descricao_vizinhanca"] = dados_hospedagem["descricao_vizinhanca"].str.split(",")
dados_hospedagem["descricao_vizinhanca"]

0       [lower queen anne is near the seattle center  ...
1       [upper queen anne is a really pleasant  unique...
2       [the convenience of being in seattle but on th...
3       [ballard is lovely  vibrant and one of the mos...
4                                                    [  ]
                              ...
3813                                                 [  ]
3814    [quiet  dead end street near i-5  the proximit...
3815                                                 [  ]
3816    [your hosts made madison valley their home whe...
3817    [despite the quiet  leafy streets of this resi...
Name: descricao_vizinhanca, Length: 3818, dtype: object

In [ ]:
dados_hospedagem.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,"[this, clean, and, comfortable, one, bedroom, ...",[lower queen anne is near the seattle center ...,1,1,1,Real Bed,"[Internet, ""Wireless Internet"", Kitchen, ""Free...",0.0,0.0,110.0
1,10.0,--,1,"[our, century, old, upper, queen, anne, house,...",[upper queen anne is a really pleasant unique...,1,1,1,Futon,"[TV, Internet, ""Wireless Internet"", Kitchen, ""...",0.0,0.0,45.0
2,10.0,--,1,"[cozy, room, in, two-bedroom, apartment, along...",[the convenience of being in seattle but on th...,1,1,1,Futon,"[TV, Internet, ""Wireless Internet"", Kitchen, ""...",0.0,0.0,55.0
3,10.0,--,1,"[very, lovely, and, cozy, room, for, one, conv...",[ballard is lovely vibrant and one of the mos...,1,1,1,Pull-out Sofa,"[Internet, ""Wireless Internet"", Kitchen, ""Free...",0.0,20.0,52.0
4,10.0,--,1,"[the, studio, at, mibbett, hollow', is, in, a,...",[ ],1,1,1,Real Bed,"[""Wireless Internet"", Kitchen, ""Free Parking o...",0.0,15.0,85.0

#Desafio 3

3.1.Devido a uma instabilidade no site da empresa, tivemos problemas com os nomes dos clientes durante o salvamento. Isso resultou em uma coluna de nomes de clientes com uma mistura de letras, maiúsculas e minúsculas, números e outros caracteres.

Sabendo disso, manipule os textos presentes na coluna Cliente para que seja obtido como resultado os nomes dos clientes em letras minúsculas, com a ausência de caracteres especiais ou números.

In [ ]:
dados_vendas["Cliente"] = dados_vendas["Cliente"].str.lower()
dados_vendas["Cliente"]

0       @ana _lucia 321
0    diego armandiu 210
0    diego armandiu 210
0    diego armandiu 210
1    isabely joanes 738
1    isabely joanes 738
1    isabely joanes 738
1    isabely joanes 738
2    isabely joanes 738
2      joão gabriel 671
2    julya meireles 914
2    julya meireles 914
3    julya meireles 914
3       maria julia 444
3       maria julia 444
3       maria julia 444
4       maria julia 444
4       pedro pasco 812
4      paulo castro 481
4     thiago fritzz 883
Name: Cliente, dtype: object

In [ ]:
dados_vendas["Cliente"] = dados_vendas["Cliente"].str.replace("[^a-zA-Z']"," ",regex=True)
dados_vendas["Cliente"] = dados_vendas["Cliente"].str.strip()
dados_vendas

  Data de venda         Cliente  Valor da compra
0    06/06/2022      ana  lucia           836.50
0    06/06/2022  diego armandiu           573.33
0    06/06/2022  diego armandiu           392.80
0    06/06/2022  diego armandiu           512.34
1    07/06/2022  isabely joanes           825.31
1    07/06/2022  isabely joanes           168.07
1    07/06/2022  isabely joanes           339.18
1    07/06/2022  isabely joanes           314.69
2    08/06/2022  isabely joanes           682.05
2    08/06/2022    jo o gabriel           386.34
2    08/06/2022  julya meireles           622.65
2    08/06/2022  julya meireles           630.79
3    09/06/2022  julya meireles           390.30
3    09/06/2022     maria julia           759.16
3    09/06/2022     maria julia           334.47
3    09/06/2022     maria julia           678.78
4    10/06/2022     maria julia           314.24
4    10/06/2022     pedro pasco           311.15
4    10/06/2022    paulo castro           899.16
4    10/06/2022   thiago fritzz           885.24

3.2.Buscando explicar a organização da identificação dos apartamentos, durante a criação do conjunto de dados, foi adicionado o texto (blocoAP). Esse texto informa que os nomes dos apartamentos estão organizados com a letra do bloco seguida do número do apartamento. No entanto, isso não traz nenhuma informação para nossos dados, sendo interessante realizar a remoção desse texto no conjunto de dados.

Com isso, manipule os textos na coluna apartamento para remover o texto (blocoAP) do DataFrame.

In [ ]:
dados_imoveis

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel
0,A101 (blocoAP),01/06/2022,05/06/2022,1000.0
0,A101 (blocoAP),01/07/2022,03/07/2022,2500.0
1,A102 (blocoAP),02/06/2022,02/06/2022,1100.0
1,A102 (blocoAP),02/07/2022,06/07/2022,2600.0
2,B201 (blocoAP),03/06/2022,07/06/2022,1200.0
2,B201 (blocoAP),03/07/2022,03/07/2022,2700.0
3,B202 (blocoAP),04/06/2022,07/06/2022,1300.0
3,B202 (blocoAP),04/07/2022,05/07/2022,2800.0
4,C301 (blocoAP),05/06/2022,10/06/2022,1400.0
4,C301 (blocoAP),05/07/2022,09/07/2022,2900.0
5,C302 (blocoAP),06/06/2022,08/06/2022,1500.0
5,C302 (blocoAP),06/07/2022,12/07/2022,1200.0
6,D401 (blocoAP),07/06/2022,07/06/2022,1600.0
6,D401 (blocoAP),07/07/2022,09/07/2022,1300.0
7,D402 (blocoAP),08/06/2022,10/06/2022,1700.0
7,D402 (blocoAP),08/07/2022,14/07/2022,1400.0
8,E501 (blocoAP),09/06/2022,10/06/2022,1800.0
8,E501 (blocoAP),09/07/2022,09/07/2022,1500.0
9,E502 (blocoAP),10/06/2022,16/06/2022,1900.0
9,E502 (blocoAP),10/07/2022,12/07/2022,1600.0
10,F601 (blocoAP),11/06/2022,17/06/2022,2000.0
10,F601 (blocoAP),11/07/2022,13/07/2022,1000.0
11,F602 (blocoAP),12/06/2022,15/06/2022,2100.0
11,F602 (blocoAP),12/07/2022,12/07/2022,1100.0
12,G701 (blocoAP),13/06/2022,19/06/2022,2200.0
12,G701 (blocoAP),13/07/2022,20/07/2022,1200.0
13,G702 (blocoAP),14/06/2022,15/06/2022,2300.0
13,G702 (blocoAP),14/07/2022,17/07/2022,2100.0
14,H801 (blocoAP),15/06/2022,18/06/2022,2400.0
14,H801 (blocoAP),15/07/2022,16/07/2022,2200.0

In [ ]:
dados_imoveis["apartamento"] = dados_imoveis["apartamento"].str.replace("\(blocoAP\)","",regex=True)
dados_imoveis["apartamento"]

0     A101
0     A101
1     A102
1     A102
2     B201
2     B201
3     B202
3     B202
4     C301
4     C301
5     C302
5     C302
6     D401
6     D401
7     D402
7     D402
8     E501
8     E501
9     E502
9     E502
10    F601
10    F601
11    F602
11    F602
12    G701
12    G701
13    G702
13    G702
14    H801
14    H801
Name: apartamento, dtype: object

#Dados de tempo (date time)

In [ ]:
datas = pd.read_json("/content/moveis_disponiveis.json")

In [ ]:
datas

          id        data  vaga_disponivel    preco
0        857  2016-01-04            False     None
1        857  2016-01-05            False     None
2        857  2016-01-06            False     None
3        857  2016-01-07            False     None
4        857  2016-01-08            False     None
...      ...         ...              ...      ...
364995  3279  2016-12-29             True  $140.00
364996  3279  2016-12-30             True  $140.00
364997  3279  2016-12-31             True  $140.00
364998  3279  2017-01-01             True  $140.00
364999  3279  2017-01-02            False     None

[365000 rows x 4 columns]

In [ ]:
datas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               365000 non-null  int64
 1   data             365000 non-null  object
 2   vaga_disponivel  365000 non-null  bool
 3   preco            270547 non-null  object
dtypes: bool(1), int64(1), object(2)
memory usage: 11.5+ MB

In [ ]:
datas["data"] = pd.to_datetime(datas["data"])
datas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               365000 non-null  int64
 1   data             365000 non-null  datetime64[ns]
 2   vaga_disponivel  365000 non-null  bool
 3   preco            270547 non-null  object
dtypes: bool(1), datetime64[ns](1), int64(1), object(1)
memory usage: 11.5+ MB

In [ ]:
datas.head()

    id       data  vaga_disponivel preco
0  857 2016-01-04            False  None
1  857 2016-01-05            False  None
2  857 2016-01-06            False  None
3  857 2016-01-07            False  None
4  857 2016-01-08            False  None

In [ ]:
datas["data"].dt.strftime("%Y-%m")

0         2016-01
1         2016-01
2         2016-01
3         2016-01
4         2016-01
           ...
364995    2016-12
364996    2016-12
364997    2016-12
364998    2017-01
364999    2017-01
Name: data, Length: 365000, dtype: object

In [ ]:
sub_set = datas.groupby(datas["data"].dt.strftime("%Y-%m"))[["vaga_disponivel"]].sum()

In [ ]:
sub_set

         vaga_disponivel
data
2016-01            16543
2016-02            20128
2016-03            23357
2016-04            22597
2016-05            23842
2016-06            23651
2016-07            22329
2016-08            22529
2016-09            22471
2016-10            23765
2016-11            23352
2016-12            24409
2017-01             1574

#Desafio

Durante as aulas desse curso, descobrimos como transformar e trabalhar com valores numéricos, por exemplo, removendo valores numéricos dentro de um texto e transformando-os em um tipo numérico, como int64 ou float64.

Sabendo disso, nessa atividade, proponho que você faça a transformação dos dados na coluna preco do conjunto de dados moveis_disponiveis.json para o tipo numérico float64. Lembrando que, antes de fazer isso, você precisa preencher os valores vazios na coluna por um valor. Uma sugestão: substitua pela string '0.0'.

In [ ]:
datas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 365000 entries, 0 to 364999
Data columns (total 4 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               365000 non-null  int64
 1   data             365000 non-null  datetime64[ns]
 2   vaga_disponivel  365000 non-null  bool
 3   preco            270547 non-null  object
dtypes: bool(1), datetime64[ns](1), int64(1), object(1)
memory usage: 11.5+ MB

In [ ]:
datas["preco"] = datas["preco"].str.replace("\$","",regex=True)
datas["preco"] = datas["preco"].str.replace("\,","",regex=True)
datas["preco"] = datas["preco"].fillna(0)
datas["preco"]

0              0
1              0
2              0
3              0
4              0
           ...
364995    140.00
364996    140.00
364997    140.00
364998    140.00
364999         0
Name: preco, Length: 365000, dtype: object

In [ ]:
datas["preco"] = datas["preco"].astype(np.float64)

Projeto vendas online etapa 4

Na coluna Data de venda, temos datas em formato 'dia/mês/ano' (dd/mm/AAAA). Transforme esses dados para o tipo datetime e busque uma forma de visualização de subconjunto que possa contribuir no objetivo do contexto que os dados estão inseridos.

In [ ]:
dados_vendas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 0 to 4
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de venda    20 non-null     object
 1   Cliente          20 non-null     object
 2   Valor da compra  20 non-null     float64
dtypes: float64(1), object(2)
memory usage: 1.2+ KB

In [ ]:
dados_vendas["Data de venda"] =  pd.to_datetime(dados_vendas["Data de venda"],format="%d/%m/%Y")

In [ ]:
dados_vendas

  Data de venda         Cliente  Valor da compra
0    2022-06-06      ana  lucia           836.50
0    2022-06-06  diego armandiu           573.33
0    2022-06-06  diego armandiu           392.80
0    2022-06-06  diego armandiu           512.34
1    2022-06-07  isabely joanes           825.31
1    2022-06-07  isabely joanes           168.07
1    2022-06-07  isabely joanes           339.18
1    2022-06-07  isabely joanes           314.69
2    2022-06-08  isabely joanes           682.05
2    2022-06-08    jo o gabriel           386.34
2    2022-06-08  julya meireles           622.65
2    2022-06-08  julya meireles           630.79
3    2022-06-09  julya meireles           390.30
3    2022-06-09     maria julia           759.16
3    2022-06-09     maria julia           334.47
3    2022-06-09     maria julia           678.78
4    2022-06-10     maria julia           314.24
4    2022-06-10     pedro pasco           311.15
4    2022-06-10    paulo castro           899.16
4    2022-06-10   thiago fritzz           885.24

O objetivo desse projeto é realizar uma análise dos resultados de um evento com os clientes de uma empresa de vendas online. Foi coletado um conjunto de dados que contém os clientes que mais gastaram com produtos dentro de 5 dias de vendas, que é o período de duração do evento. Essa análise vai identificar o cliente com a maior compra na semana, que irá receber um prêmio da loja, e posteriormente, ela pode ajudar a empresa a criar novas estratégias para atrair mais clientes.

In [ ]:
total = dados_vendas.groupby("Cliente")[["Valor da compra"]].sum()
total

                Valor da compra
Cliente
ana  lucia               836.50
diego armandiu          1478.47
isabely joanes          2329.30
jo o gabriel             386.34
julya meireles          1643.74
maria julia             2086.65
paulo castro             899.16
pedro pasco              311.15
thiago fritzz            885.24

Segundo projeto Etapa 4

Nas colunas datas_de_pagamento e datas_combinadas_pagamento, temos datas em formato 'dia/mês/ano' (dd/mm/AAAA). Transforme esses dados para o tipo datetime e busque uma forma de visualização de subconjunto que possa contribuir no objetivo do contexto que os dados estão inseridos.

In [ ]:
dados_imoveis

   apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0        A101                  01/06/2022         05/06/2022         1000.0
0        A101                  01/07/2022         03/07/2022         2500.0
1        A102                  02/06/2022         02/06/2022         1100.0
1        A102                  02/07/2022         06/07/2022         2600.0
2        B201                  03/06/2022         07/06/2022         1200.0
2        B201                  03/07/2022         03/07/2022         2700.0
3        B202                  04/06/2022         07/06/2022         1300.0
3        B202                  04/07/2022         05/07/2022         2800.0
4        C301                  05/06/2022         10/06/2022         1400.0
4        C301                  05/07/2022         09/07/2022         2900.0
5        C302                  06/06/2022         08/06/2022         1500.0
5        C302                  06/07/2022         12/07/2022         1200.0
6        D401                  07/06/2022         07/06/2022         1600.0
6        D401                  07/07/2022         09/07/2022         1300.0
7        D402                  08/06/2022         10/06/2022         1700.0
7        D402                  08/07/2022         14/07/2022         1400.0
8        E501                  09/06/2022         10/06/2022         1800.0
8        E501                  09/07/2022         09/07/2022         1500.0
9        E502                  10/06/2022         16/06/2022         1900.0
9        E502                  10/07/2022         12/07/2022         1600.0
10       F601                  11/06/2022         17/06/2022         2000.0
10       F601                  11/07/2022         13/07/2022         1000.0
11       F602                  12/06/2022         15/06/2022         2100.0
11       F602                  12/07/2022         12/07/2022         1100.0
12       G701                  13/06/2022         19/06/2022         2200.0
12       G701                  13/07/2022         20/07/2022         1200.0
13       G702                  14/06/2022         15/06/2022         2300.0
13       G702                  14/07/2022         17/07/2022         2100.0
14       H801                  15/06/2022         18/06/2022         2400.0
14       H801                  15/07/2022         16/07/2022         2200.0

In [ ]:
dados_imoveis.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 0 to 14
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     object
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     float64
dtypes: float64(1), object(3)
memory usage: 1.2+ KB

In [ ]:
dados_imoveis["datas_combinadas_pagamento"] =pd.to_datetime(dados_imoveis["datas_combinadas_pagamento"],format="%d/%m/%Y")
dados_imoveis

   apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0        A101                  2022-06-01         05/06/2022         1000.0
0        A101                  2022-07-01         03/07/2022         2500.0
1        A102                  2022-06-02         02/06/2022         1100.0
1        A102                  2022-07-02         06/07/2022         2600.0
2        B201                  2022-06-03         07/06/2022         1200.0
2        B201                  2022-07-03         03/07/2022         2700.0
3        B202                  2022-06-04         07/06/2022         1300.0
3        B202                  2022-07-04         05/07/2022         2800.0
4        C301                  2022-06-05         10/06/2022         1400.0
4        C301                  2022-07-05         09/07/2022         2900.0
5        C302                  2022-06-06         08/06/2022         1500.0
5        C302                  2022-07-06         12/07/2022         1200.0
6        D401                  2022-06-07         07/06/2022         1600.0
6        D401                  2022-07-07         09/07/2022         1300.0
7        D402                  2022-06-08         10/06/2022         1700.0
7        D402                  2022-07-08         14/07/2022         1400.0
8        E501                  2022-06-09         10/06/2022         1800.0
8        E501                  2022-07-09         09/07/2022         1500.0
9        E502                  2022-06-10         16/06/2022         1900.0
9        E502                  2022-07-10         12/07/2022         1600.0
10       F601                  2022-06-11         17/06/2022         2000.0
10       F601                  2022-07-11         13/07/2022         1000.0
11       F602                  2022-06-12         15/06/2022         2100.0
11       F602                  2022-07-12         12/07/2022         1100.0
12       G701                  2022-06-13         19/06/2022         2200.0
12       G701                  2022-07-13         20/07/2022         1200.0
13       G702                  2022-06-14         15/06/2022         2300.0
13       G702                  2022-07-14         17/07/2022         2100.0
14       H801                  2022-06-15         18/06/2022         2400.0
14       H801                  2022-07-15         16/07/2022         2200.0

In [ ]:
dados_imoveis.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 0 to 14
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     datetime64[ns]
 2   datas_de_pagamento          30 non-null     object
 3   valor_aluguel               30 non-null     float64
dtypes: datetime64[ns](1), float64(1), object(2)
memory usage: 1.2+ KB

In [ ]:
dados_imoveis["datas_de_pagamento"] = pd.to_datetime(dados_imoveis["datas_de_pagamento"],format="%d/%m/%Y")
dados_imoveis.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30 entries, 0 to 14
Data columns (total 4 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   apartamento                 30 non-null     object
 1   datas_combinadas_pagamento  30 non-null     datetime64[ns]
 2   datas_de_pagamento          30 non-null     datetime64[ns]
 3   valor_aluguel               30 non-null     float64
dtypes: datetime64[ns](2), float64(1), object(1)
memory usage: 1.2+ KB

A administração de condomínios é uma tarefa que requer muita atenção e organização. Entre as diversas responsabilidades da gestão está o recebimento dos aluguéis dos locatários. Para garantir uma boa saúde financeira do empreendimento, é fundamental que esses pagamentos sejam feitos de forma regular e pontual. No entanto, sabemos que nem sempre isso acontece. Pensando nisso, proponho um desafio de tratamento de dados com o objetivo de analisar o atraso no pagamento de aluguéis no condomínio fictício de alguns moradores.

In [ ]:
dados_imoveis

   apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0        A101                  2022-06-01         2022-06-05         1000.0
0        A101                  2022-07-01         2022-07-03         2500.0
1        A102                  2022-06-02         2022-06-02         1100.0
1        A102                  2022-07-02         2022-07-06         2600.0
2        B201                  2022-06-03         2022-06-07         1200.0
2        B201                  2022-07-03         2022-07-03         2700.0
3        B202                  2022-06-04         2022-06-07         1300.0
3        B202                  2022-07-04         2022-07-05         2800.0
4        C301                  2022-06-05         2022-06-10         1400.0
4        C301                  2022-07-05         2022-07-09         2900.0
5        C302                  2022-06-06         2022-06-08         1500.0
5        C302                  2022-07-06         2022-07-12         1200.0
6        D401                  2022-06-07         2022-06-07         1600.0
6        D401                  2022-07-07         2022-07-09         1300.0
7        D402                  2022-06-08         2022-06-10         1700.0
7        D402                  2022-07-08         2022-07-14         1400.0
8        E501                  2022-06-09         2022-06-10         1800.0
8        E501                  2022-07-09         2022-07-09         1500.0
9        E502                  2022-06-10         2022-06-16         1900.0
9        E502                  2022-07-10         2022-07-12         1600.0
10       F601                  2022-06-11         2022-06-17         2000.0
10       F601                  2022-07-11         2022-07-13         1000.0
11       F602                  2022-06-12         2022-06-15         2100.0
11       F602                  2022-07-12         2022-07-12         1100.0
12       G701                  2022-06-13         2022-06-19         2200.0
12       G701                  2022-07-13         2022-07-20         1200.0
13       G702                  2022-06-14         2022-06-15         2300.0
13       G702                  2022-07-14         2022-07-17         2100.0
14       H801                  2022-06-15         2022-06-18         2400.0
14       H801                  2022-07-15         2022-07-16         2200.0

In [ ]:
dados_imoveis["atraso_dias"] = (dados_imoveis["datas_de_pagamento"] - dados_imoveis["datas_combinadas_pagamento"]).dt.days
dados_imoveis

,apartamento,datas_combinadas_pagamento,datas_de_pagamento,valor_aluguel,atraso_dias
0,A101,2022-06-01,2022-06-05,1000.0,4
0,A101,2022-07-01,2022-07-03,2500.0,2
1,A102,2022-06-02,2022-06-02,1100.0,0
1,A102,2022-07-02,2022-07-06,2600.0,4
2,B201,2022-06-03,2022-06-07,1200.0,4
2,B201,2022-07-03,2022-07-03,2700.0,0
3,B202,2022-06-04,2022-06-07,1300.0,3
3,B202,2022-07-04,2022-07-05,2800.0,1
4,C301,2022-06-05,2022-06-10,1400.0,5
4,C301,2022-07-05,2022-07-09,2900.0,4
5,C302,2022-06-06,2022-06-08,1500.0,2
5,C302,2022-07-06,2022-07-12,1200.0,6
6,D401,2022-06-07,2022-06-07,1600.0,0
6,D401,2022-07-07,2022-07-09,1300.0,2
7,D402,2022-06-08,2022-06-10,1700.0,2
7,D402,2022-07-08,2022-07-14,1400.0,6
8,E501,2022-06-09,2022-06-10,1800.0,1
8,E501,2022-07-09,2022-07-09,1500.0,0
9,E502,2022-06-10,2022-06-16,1900.0,6
9,E502,2022-07-10,2022-07-12,1600.0,2
10,F601,2022-06-11,2022-06-17,2000.0,6
10,F601,2022-07-11,2022-07-13,1000.0,2
11,F602,2022-06-12,2022-06-15,2100.0,3
11,F602,2022-07-12,2022-07-12,1100.0,0
12,G701,2022-06-13,2022-06-19,2200.0,6
12,G701,2022-07-13,2022-07-20,1200.0,7
13,G702,2022-06-14,2022-06-15,2300.0,1
13,G702,2022-07-14,2022-07-17,2100.0,3
14,H801,2022-06-15,2022-06-18,2400.0,3
14,H801,2022-07-15,2022-07-16,2200.0,1

In [ ]:
tempo_atraso = dados_imoveis.groupby("apartamento")[["atraso_dias"]].mean()
tempo_atraso

             atraso_dias
apartamento
A101                 3.0
A102                 2.0
B201                 2.0
B202                 2.0
C301                 4.5
C302                 4.0
D401                 1.0
D402                 4.0
E501                 0.5
E502                 4.0
F601                 4.0
F602                 1.5
G701                 6.5
G702                 2.0
H801                 2.0